services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe.rule=Host(`erpnext.jackadam.top`)" # 替换为你的域名
      - "traefik.http.services.frappe.loadbalancer.server.port=8080"
