services:
  traefik:
    image: traefik:v3.3
    command:
      # 测试环境，启用api
      - "--api.insecure=true"
      # 启用监听docker
      - "--providers.docker"
      # 入口点 HTTP 80
      - "--entryPoints.web.address=:80"
      # 入口点 HTTPS 443
      - "--entryPoints.websecure.address=:443"
    ports:
      - "${HTTP_PUBLISH_PORT}:80"    # 主机端口:容器端口
      - "${HTTPS_PUBLISH_PORT}:443"  # 主机端口:容器端口
      - "${TRAEFIK_PORT}:8080"       # 主机端口:容器端口
    volumes:
      # 监听docker映射
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`erpnext.jackadam.top`)" # 替换为你的域名
      - "traefik.http.services.gitea.loadbalancer.server.port=8080"
